apiVersion: v1alpha1
kind: Lab
metadata:
  name: ocp4-getting-started-module-3
  displayName: OpenShift 4 Getting Started Module 3
  description: |
    This is a description of the third module of the getting started
    interactive lab. It is *Asciidoc*.
spec:
  attributes:
    module: "3"
  checkpoints: []
