apiVersion: v1alpha1
kind: Lab
metadata:
  name: ocp4-getting-started-module-2
  displayName: OpenShift 4 Getting Started Module 2
  description: |
    This is a description of the second module of the getting started
    interactive lab. It is *Asciidoc*.
spec:
  attributes:
    module: "2"
  checkpoints: []
